# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ram0/ram0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram0 || ORIG_REF_NAME==ram0} -quiet] -quiet

# Block Designs: D:/lab11/design_11/design_11.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_11 || ORIG_REF_NAME==design_11} -quiet] -quiet

# IP: D:/lab11/design_11/ip/design_11_cg_fpga_0_0/design_11_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_11_cg_fpga_0_0 || ORIG_REF_NAME==design_11_cg_fpga_0_0} -quiet] -quiet

# IP: D:/lab11/design_11/ip/design_11_adpt_out_0_0/design_11_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_11_adpt_out_0_0 || ORIG_REF_NAME==design_11_adpt_out_0_0} -quiet] -quiet

# IP: D:/lab11/design_11/ip/design_11_adpt_in_0_1/design_11_adpt_in_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_11_adpt_in_0_1 || ORIG_REF_NAME==design_11_adpt_in_0_1} -quiet] -quiet

# IP: D:/lab11/design_11/ip/design_11_ram_dp0_256x8_0_0/design_11_ram_dp0_256x8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_11_ram_dp0_256x8_0_0 || ORIG_REF_NAME==design_11_ram_dp0_256x8_0_0} -quiet] -quiet

# IP: ip/ram0/ram0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram0 || ORIG_REF_NAME==ram0} -quiet] -quiet

# XDC: D:/lab11/design_11/design_11_ooc.xdc
