# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab77/design_77/design_77.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77 || ORIG_REF_NAME==design_77} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_cg_fpga_0_0/design_77_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_cg_fpga_0_0 || ORIG_REF_NAME==design_77_cg_fpga_0_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_adpt_in_0_0/design_77_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_adpt_in_0_0 || ORIG_REF_NAME==design_77_adpt_in_0_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_adpt_out_0_0/design_77_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_adpt_out_0_0 || ORIG_REF_NAME==design_77_adpt_out_0_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_dff_0_0/design_77_dff_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_dff_0_0 || ORIG_REF_NAME==design_77_dff_0_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_or2_0_0/design_77_or2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_or2_0_0 || ORIG_REF_NAME==design_77_or2_0_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_nor4_0_0/design_77_nor4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_nor4_0_0 || ORIG_REF_NAME==design_77_nor4_0_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_dff_1_0/design_77_dff_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_dff_1_0 || ORIG_REF_NAME==design_77_dff_1_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_dff_2_0/design_77_dff_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_dff_2_0 || ORIG_REF_NAME==design_77_dff_2_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_dff_3_0/design_77_dff_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_dff_3_0 || ORIG_REF_NAME==design_77_dff_3_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_dff_4_0/design_77_dff_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_dff_4_0 || ORIG_REF_NAME==design_77_dff_4_0} -quiet] -quiet

# IP: d:/lab77/design_77/ip/design_77_xlconstant_0_0/design_77_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_77_xlconstant_0_0 || ORIG_REF_NAME==design_77_xlconstant_0_0} -quiet] -quiet

# XDC: D:/lab77/design_77/design_77_ooc.xdc
