@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 16 16:47:05 +0800 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim complete_monitor_test_behav -key {Behavioral:sim_2:Functional:complete_monitor_test} -tclbatch complete_monitor_test.tcl -protoinst "protoinst_files/design_3.protoinst" -log simulate.log"
call xsim  complete_monitor_test_behav -key {Behavioral:sim_2:Functional:complete_monitor_test} -tclbatch complete_monitor_test.tcl -protoinst "protoinst_files/design_3.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
