# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab6/design_6/design_6.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6 || ORIG_REF_NAME==design_6} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_cg_fpga_0_0/design_6_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_cg_fpga_0_0 || ORIG_REF_NAME==design_6_cg_fpga_0_0} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_adpt_in_0_0/design_6_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_adpt_in_0_0 || ORIG_REF_NAME==design_6_adpt_in_0_0} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_adpt_out_0_0/design_6_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_adpt_out_0_0 || ORIG_REF_NAME==design_6_adpt_out_0_0} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_dff4_0_0/design_6_dff4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_dff4_0_0 || ORIG_REF_NAME==design_6_dff4_0_0} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_m7482_0_0/design_6_m7482_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_m7482_0_0 || ORIG_REF_NAME==design_6_m7482_0_0} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_xor2_0_0/design_6_xor2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_xor2_0_0 || ORIG_REF_NAME==design_6_xor2_0_0} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_m7482_0_1/design_6_m7482_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_m7482_0_1 || ORIG_REF_NAME==design_6_m7482_0_1} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_xor2_0_1/design_6_xor2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_xor2_0_1 || ORIG_REF_NAME==design_6_xor2_0_1} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_xor2_0_2/design_6_xor2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_xor2_0_2 || ORIG_REF_NAME==design_6_xor2_0_2} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_xor2_0_3/design_6_xor2_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_xor2_0_3 || ORIG_REF_NAME==design_6_xor2_0_3} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_xor2_0_4/design_6_xor2_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_xor2_0_4 || ORIG_REF_NAME==design_6_xor2_0_4} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_dff4_1_0/design_6_dff4_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_dff4_1_0 || ORIG_REF_NAME==design_6_dff4_1_0} -quiet] -quiet

# IP: D:/lab6/design_6/ip/design_6_m7482_2_1/design_6_m7482_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_m7482_2_1 || ORIG_REF_NAME==design_6_m7482_2_1} -quiet] -quiet

# XDC: D:/lab6/design_6/design_6_ooc.xdc
