# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab8/design_8/design_8.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_8 || ORIG_REF_NAME==design_8} -quiet] -quiet

# IP: d:/lab8/design_8/ip/design_8_cg_fpga_0_0/design_8_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_8_cg_fpga_0_0 || ORIG_REF_NAME==design_8_cg_fpga_0_0} -quiet] -quiet

# IP: d:/lab8/design_8/ip/design_8_adpt_in_0_0/design_8_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_8_adpt_in_0_0 || ORIG_REF_NAME==design_8_adpt_in_0_0} -quiet] -quiet

# IP: d:/lab8/design_8/ip/design_8_adpt_out_0_0/design_8_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_8_adpt_out_0_0 || ORIG_REF_NAME==design_8_adpt_out_0_0} -quiet] -quiet

# IP: d:/lab8/design_8/ip/design_8_m74LS161_0_0/design_8_m74LS161_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_8_m74LS161_0_0 || ORIG_REF_NAME==design_8_m74LS161_0_0} -quiet] -quiet

# IP: d:/lab8/design_8/ip/design_8_m74LS194_0_0/design_8_m74LS194_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_8_m74LS194_0_0 || ORIG_REF_NAME==design_8_m74LS194_0_0} -quiet] -quiet

# IP: d:/lab8/design_8/ip/design_8_m74LS138_0_0/design_8_m74LS138_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_8_m74LS138_0_0 || ORIG_REF_NAME==design_8_m74LS138_0_0} -quiet] -quiet

# IP: d:/lab8/design_8/ip/design_8_m74ls04_0_0/design_8_m74ls04_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_8_m74ls04_0_0 || ORIG_REF_NAME==design_8_m74ls04_0_0} -quiet] -quiet

# XDC: D:/lab8/design_8/design_8_ooc.xdc
