# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab4_4/design_4/design_4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4 || ORIG_REF_NAME==design_4} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_cg_fpga_0_0/design_4_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_cg_fpga_0_0 || ORIG_REF_NAME==design_4_cg_fpga_0_0} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_adpt_in_0_0/design_4_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_adpt_in_0_0 || ORIG_REF_NAME==design_4_adpt_in_0_0} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_0_0/design_4_and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_0_0 || ORIG_REF_NAME==design_4_and2_0_0} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_1_0/design_4_and2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_1_0 || ORIG_REF_NAME==design_4_and2_1_0} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_0_1/design_4_and2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_0_1 || ORIG_REF_NAME==design_4_and2_0_1} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_1_1/design_4_and2_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_1_1 || ORIG_REF_NAME==design_4_and2_1_1} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_0_2/design_4_and2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_0_2 || ORIG_REF_NAME==design_4_and2_0_2} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_1_2/design_4_and2_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_1_2 || ORIG_REF_NAME==design_4_and2_1_2} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_2_0/design_4_and2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_2_0 || ORIG_REF_NAME==design_4_and2_2_0} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_3_0/design_4_and2_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_3_0 || ORIG_REF_NAME==design_4_and2_3_0} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_0_3/design_4_and2_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_0_3 || ORIG_REF_NAME==design_4_and2_0_3} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_1_3/design_4_and2_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_1_3 || ORIG_REF_NAME==design_4_and2_1_3} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_2_1/design_4_and2_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_2_1 || ORIG_REF_NAME==design_4_and2_2_1} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_and2_3_1/design_4_and2_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_and2_3_1 || ORIG_REF_NAME==design_4_and2_3_1} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_or3_0_0/design_4_or3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_or3_0_0 || ORIG_REF_NAME==design_4_or3_0_0} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_or3_0_1/design_4_or3_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_or3_0_1 || ORIG_REF_NAME==design_4_or3_0_1} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_or3_0_2/design_4_or3_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_or3_0_2 || ORIG_REF_NAME==design_4_or3_0_2} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_or3_0_3/design_4_or3_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_or3_0_3 || ORIG_REF_NAME==design_4_or3_0_3} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_adpt_out_0_0/design_4_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_adpt_out_0_0 || ORIG_REF_NAME==design_4_adpt_out_0_0} -quiet] -quiet

# IP: d:/lab4_4/design_4/ip/design_4_xlconstant_0_0/design_4_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xlconstant_0_0 || ORIG_REF_NAME==design_4_xlconstant_0_0} -quiet] -quiet

# XDC: D:/lab4_4/design_4/design_4_ooc.xdc
