# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab7/design_7/design_7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_7 || ORIG_REF_NAME==design_7} -quiet] -quiet

# IP: D:/lab7/design_7/ip/design_7_cg_fpga_0_0/design_7_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_7_cg_fpga_0_0 || ORIG_REF_NAME==design_7_cg_fpga_0_0} -quiet] -quiet

# IP: D:/lab7/design_7/ip/design_7_adpt_in_0_0/design_7_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_7_adpt_in_0_0 || ORIG_REF_NAME==design_7_adpt_in_0_0} -quiet] -quiet

# IP: D:/lab7/design_7/ip/design_7_adpt_out_0_0/design_7_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_7_adpt_out_0_0 || ORIG_REF_NAME==design_7_adpt_out_0_0} -quiet] -quiet

# IP: D:/lab7/design_7/ip/design_7_dff_0_0/design_7_dff_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_7_dff_0_0 || ORIG_REF_NAME==design_7_dff_0_0} -quiet] -quiet

# IP: D:/lab7/design_7/ip/design_7_dff_1_0/design_7_dff_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_7_dff_1_0 || ORIG_REF_NAME==design_7_dff_1_0} -quiet] -quiet

# IP: D:/lab7/design_7/ip/design_7_dff_2_0/design_7_dff_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_7_dff_2_0 || ORIG_REF_NAME==design_7_dff_2_0} -quiet] -quiet

# IP: D:/lab7/design_7/ip/design_7_dff_3_0/design_7_dff_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_7_dff_3_0 || ORIG_REF_NAME==design_7_dff_3_0} -quiet] -quiet

# IP: D:/lab7/design_7/ip/design_7_xlconstant_0_0/design_7_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_7_xlconstant_0_0 || ORIG_REF_NAME==design_7_xlconstant_0_0} -quiet] -quiet

# XDC: D:/lab7/design_7/design_7_ooc.xdc
