# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: E:/lab_ini_1/design_int_1/design_int_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1 || ORIG_REF_NAME==design_int_1} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_cg_fpga_0_0/design_int_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_cg_fpga_0_0 || ORIG_REF_NAME==design_int_1_cg_fpga_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_adpt_in_0_0/design_int_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_adpt_in_0_0 || ORIG_REF_NAME==design_int_1_adpt_in_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_adpt_out_0_0/design_int_1_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_adpt_out_0_0 || ORIG_REF_NAME==design_int_1_adpt_out_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_m74LS194_0_0/design_int_1_m74LS194_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_m74LS194_0_0 || ORIG_REF_NAME==design_int_1_m74LS194_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_m74LS194_0_1/design_int_1_m74LS194_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_m74LS194_0_1 || ORIG_REF_NAME==design_int_1_m74LS194_0_1} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_m74LS194_0_2/design_int_1_m74LS194_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_m74LS194_0_2 || ORIG_REF_NAME==design_int_1_m74LS194_0_2} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_m74LS194_0_3/design_int_1_m74LS194_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_m74LS194_0_3 || ORIG_REF_NAME==design_int_1_m74LS194_0_3} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_dff_1_0/design_int_1_dff_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_dff_1_0 || ORIG_REF_NAME==design_int_1_dff_1_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_not1_1_0/design_int_1_not1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_not1_1_0 || ORIG_REF_NAME==design_int_1_not1_1_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_xlconstant_0_0/design_int_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_xlconstant_0_0 || ORIG_REF_NAME==design_int_1_xlconstant_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_xlconstant_0_2/design_int_1_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_xlconstant_0_2 || ORIG_REF_NAME==design_int_1_xlconstant_0_2} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_or2_0_1/design_int_1_or2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_or2_0_1 || ORIG_REF_NAME==design_int_1_or2_0_1} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_or2_0_2/design_int_1_or2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_or2_0_2 || ORIG_REF_NAME==design_int_1_or2_0_2} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_dff_2_0/design_int_1_dff_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_dff_2_0 || ORIG_REF_NAME==design_int_1_dff_2_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_and8_0_0/design_int_1_and8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_and8_0_0 || ORIG_REF_NAME==design_int_1_and8_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_m7482_0_0/design_int_1_m7482_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_m7482_0_0 || ORIG_REF_NAME==design_int_1_m7482_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_m7482_0_1/design_int_1_m7482_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_m7482_0_1 || ORIG_REF_NAME==design_int_1_m7482_0_1} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_m7482_0_2/design_int_1_m7482_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_m7482_0_2 || ORIG_REF_NAME==design_int_1_m7482_0_2} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_m7482_0_3/design_int_1_m7482_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_m7482_0_3 || ORIG_REF_NAME==design_int_1_m7482_0_3} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_dff_1_1/design_int_1_dff_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_dff_1_1 || ORIG_REF_NAME==design_int_1_dff_1_1} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_adpt_in3_0_0/design_int_1_adpt_in3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_adpt_in3_0_0 || ORIG_REF_NAME==design_int_1_adpt_in3_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_xor2_0_0/design_int_1_xor2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_xor2_0_0 || ORIG_REF_NAME==design_int_1_xor2_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_decoder_5to25_single_0_0/design_int_1_decoder_5to25_single_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_decoder_5to25_single_0_0 || ORIG_REF_NAME==design_int_1_decoder_5to25_single_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_xlconstant_0_1/design_int_1_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_xlconstant_0_1 || ORIG_REF_NAME==design_int_1_xlconstant_0_1} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_m74LS161_0_0/design_int_1_m74LS161_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_m74LS161_0_0 || ORIG_REF_NAME==design_int_1_m74LS161_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_dff_0_0/design_int_1_dff_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_dff_0_0 || ORIG_REF_NAME==design_int_1_dff_0_0} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_not1_1_1/design_int_1_not1_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_not1_1_1 || ORIG_REF_NAME==design_int_1_not1_1_1} -quiet] -quiet

# IP: E:/lab_ini_1/design_int_1/ip/design_int_1_and2_0_0/design_int_1_and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_int_1_and2_0_0 || ORIG_REF_NAME==design_int_1_and2_0_0} -quiet] -quiet

# XDC: E:/lab_ini_1/design_int_1/design_int_1_ooc.xdc
