# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab5_5/design_5/design_5.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5 || ORIG_REF_NAME==design_5} -quiet] -quiet

# IP: d:/lab5_5/design_5/ip/design_5_cg_fpga_0_0/design_5_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_cg_fpga_0_0 || ORIG_REF_NAME==design_5_cg_fpga_0_0} -quiet] -quiet

# IP: d:/lab5_5/design_5/ip/design_5_adpt_in_0_0/design_5_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_adpt_in_0_0 || ORIG_REF_NAME==design_5_adpt_in_0_0} -quiet] -quiet

# IP: d:/lab5_5/design_5/ip/design_5_dff4_0_0/design_5_dff4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_dff4_0_0 || ORIG_REF_NAME==design_5_dff4_0_0} -quiet] -quiet

# IP: d:/lab5_5/design_5/ip/design_5_dff4_1_0/design_5_dff4_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_dff4_1_0 || ORIG_REF_NAME==design_5_dff4_1_0} -quiet] -quiet

# IP: d:/lab5_5/design_5/ip/design_5_adpt_out_0_0/design_5_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_adpt_out_0_0 || ORIG_REF_NAME==design_5_adpt_out_0_0} -quiet] -quiet

# IP: d:/lab5_5/design_5/ip/design_5_shifter_0_0/design_5_shifter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_shifter_0_0 || ORIG_REF_NAME==design_5_shifter_0_0} -quiet] -quiet

# IP: d:/lab5_5/design_5/ip/design_5_dff4_2_0/design_5_dff4_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_dff4_2_0 || ORIG_REF_NAME==design_5_dff4_2_0} -quiet] -quiet

# IP: d:/lab5_5/design_5/ip/design_5_adder4_0_0/design_5_adder4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_adder4_0_0 || ORIG_REF_NAME==design_5_adder4_0_0} -quiet] -quiet

# XDC: D:/lab5_5/design_5/design_5_ooc.xdc
