# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: E:/lab13/design_13/design_13.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13 || ORIG_REF_NAME==design_13} -quiet] -quiet

# IP: E:/lab13/design_13/ip/design_13_cg_fpga_0_0/design_13_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13_cg_fpga_0_0 || ORIG_REF_NAME==design_13_cg_fpga_0_0} -quiet] -quiet

# IP: E:/lab13/design_13/ip/design_13_m74LS161_0_0/design_13_m74LS161_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13_m74LS161_0_0 || ORIG_REF_NAME==design_13_m74LS161_0_0} -quiet] -quiet

# IP: E:/lab13/design_13/ip/design_13_m74LS161_1_0/design_13_m74LS161_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13_m74LS161_1_0 || ORIG_REF_NAME==design_13_m74LS161_1_0} -quiet] -quiet

# IP: E:/lab13/design_13/ip/design_13_adpt_in_0_0/design_13_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13_adpt_in_0_0 || ORIG_REF_NAME==design_13_adpt_in_0_0} -quiet] -quiet

# IP: E:/lab13/design_13/ip/design_13_adpt_out_0_0/design_13_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13_adpt_out_0_0 || ORIG_REF_NAME==design_13_adpt_out_0_0} -quiet] -quiet

# IP: E:/lab13/design_13/ip/design_13_UIR_0_0/design_13_UIR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13_UIR_0_0 || ORIG_REF_NAME==design_13_UIR_0_0} -quiet] -quiet

# IP: E:/lab13/design_13/ip/design_13_addr_adpt_0_0/design_13_addr_adpt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13_addr_adpt_0_0 || ORIG_REF_NAME==design_13_addr_adpt_0_0} -quiet] -quiet

# IP: E:/lab13/design_13/ip/design_13_xlconstant_0_0/design_13_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13_xlconstant_0_0 || ORIG_REF_NAME==design_13_xlconstant_0_0} -quiet] -quiet

# IP: E:/lab13/design_13/ip/design_13_rom2_256x24_0_0/design_13_rom2_256x24_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_13_rom2_256x24_0_0 || ORIG_REF_NAME==design_13_rom2_256x24_0_0} -quiet] -quiet

# XDC: E:/lab13/design_13/design_13_ooc.xdc
