# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab10_/design_10/design_10.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_10 || ORIG_REF_NAME==design_10} -quiet] -quiet

# IP: D:/lab10_/design_10/ip/design_10_cg_fpga_0_0/design_10_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_10_cg_fpga_0_0 || ORIG_REF_NAME==design_10_cg_fpga_0_0} -quiet] -quiet

# IP: D:/lab10_/design_10/ip/design_10_adpt_in_0_0/design_10_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_10_adpt_in_0_0 || ORIG_REF_NAME==design_10_adpt_in_0_0} -quiet] -quiet

# IP: D:/lab10_/design_10/ip/design_10_adpt_out_0_0/design_10_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_10_adpt_out_0_0 || ORIG_REF_NAME==design_10_adpt_out_0_0} -quiet] -quiet

# IP: D:/lab10_/design_10/ip/design_10_rom0_64x24_0_0/design_10_rom0_64x24_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_10_rom0_64x24_0_0 || ORIG_REF_NAME==design_10_rom0_64x24_0_0} -quiet] -quiet

# IP: ip/rom0/rom0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom0 || ORIG_REF_NAME==rom0} -quiet] -quiet

# XDC: D:/lab10_/design_10/design_10_ooc.xdc
