# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab9/design_9/design_9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_9 || ORIG_REF_NAME==design_9} -quiet] -quiet

# IP: d:/lab9/design_9/ip/design_9_cg_fpga_0_0/design_9_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_9_cg_fpga_0_0 || ORIG_REF_NAME==design_9_cg_fpga_0_0} -quiet] -quiet

# IP: d:/lab9/design_9/ip/design_9_CNT4B_0_0/design_9_CNT4B_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_9_CNT4B_0_0 || ORIG_REF_NAME==design_9_CNT4B_0_0} -quiet] -quiet

# IP: d:/lab9/design_9/ip/design_9_DECL7SEG_0_0/design_9_DECL7SEG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_9_DECL7SEG_0_0 || ORIG_REF_NAME==design_9_DECL7SEG_0_0} -quiet] -quiet

# IP: d:/lab9/design_9/ip/design_9_adpt_in_0_0/design_9_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_9_adpt_in_0_0 || ORIG_REF_NAME==design_9_adpt_in_0_0} -quiet] -quiet

# IP: d:/lab9/design_9/ip/design_9_adpt_out_0_0/design_9_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_9_adpt_out_0_0 || ORIG_REF_NAME==design_9_adpt_out_0_0} -quiet] -quiet

# XDC: D:/lab9/design_9/design_9_ooc.xdc
