@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Oct 16 09:16:20 +0800 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_design_2_behav -key {Behavioral:sim_1:Functional:tb_design_2} -tclbatch tb_design_2.tcl -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/zlcfq_inst_0.protoinst" -protoinst "protoinst_files/zlcfq_inst_1.protoinst" -log simulate.log"
call xsim  tb_design_2_behav -key {Behavioral:sim_1:Functional:tb_design_2} -tclbatch tb_design_2.tcl -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/zlcfq_inst_0.protoinst" -protoinst "protoinst_files/zlcfq_inst_1.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
