# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/lab11/design_11/ip/design_11_ram_dp0_256x8_0_0/design_11_ram_dp0_256x8_0_0.xci
# IP: The module: 'design_11_ram_dp0_256x8_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/lab11/project_11/project_11.srcs/sources_1/ip/ram0/ram0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram0 || ORIG_REF_NAME==ram0} -quiet] -quiet

# IP: D:/lab11/design_11/ip/design_11_ram_dp0_256x8_0_0/design_11_ram_dp0_256x8_0_0.xci
# IP: The module: 'design_11_ram_dp0_256x8_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/lab11/project_11/project_11.srcs/sources_1/ip/ram0/ram0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram0 || ORIG_REF_NAME==ram0} -quiet] -quiet
