# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/design_12_2_cg_fpga_0_0.xci
# IP: The module: 'design_12_2_cg_fpga_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_gpio_0_0/cg_fpga_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_axi_gpio_0_0 || ORIG_REF_NAME==cg_fpga_axi_gpio_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_0/cg_fpga_cg_fpga_axi_gpio_o1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_1/cg_fpga_cg_fpga_axi_gpio_o1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_i1_0/cg_fpga_cg_fpga_axi_gpio_i1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_uartlite_0_0/cg_fpga_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_axi_uartlite_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_intc_0_0/cg_fpga_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_axi_intc_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_rst_ps7_0_50M_0/cg_fpga_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_rst_ps7_0_50M_0 || ORIG_REF_NAME==cg_fpga_rst_ps7_0_50M_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xbar_1/cg_fpga_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xbar_1 || ORIG_REF_NAME==cg_fpga_xbar_1} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_auto_pc_0/cg_fpga_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_auto_pc_0 || ORIG_REF_NAME==cg_fpga_auto_pc_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconcat_0_0/cg_fpga_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconcat_0_0 || ORIG_REF_NAME==cg_fpga_xlconcat_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconcat_1_0/cg_fpga_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconcat_1_0 || ORIG_REF_NAME==cg_fpga_xlconcat_1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_v_vid_in_axi4s_0_0/cg_fpga_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cg_fpga_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconcat_2_0/cg_fpga_xlconcat_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconcat_2_0 || ORIG_REF_NAME==cg_fpga_xlconcat_2_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconcat_3_0/cg_fpga_xlconcat_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconcat_3_0 || ORIG_REF_NAME==cg_fpga_xlconcat_3_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlslice_0_2/cg_fpga_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlslice_0_2 || ORIG_REF_NAME==cg_fpga_xlslice_0_2} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlslice_0_3/cg_fpga_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlslice_0_3 || ORIG_REF_NAME==cg_fpga_xlslice_0_3} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlslice_1_0/cg_fpga_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlslice_1_0 || ORIG_REF_NAME==cg_fpga_xlslice_1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconstant_0_0/cg_fpga_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconstant_0_0 || ORIG_REF_NAME==cg_fpga_xlconstant_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xbar_0/cg_fpga_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xbar_0 || ORIG_REF_NAME==cg_fpga_xbar_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_auto_pc_1/cg_fpga_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_auto_pc_1 || ORIG_REF_NAME==cg_fpga_auto_pc_1} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_vdma_0_0/cg_fpga_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_axi_vdma_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_processing_system7_0_0/cg_fpga_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_processing_system7_0_0 || ORIG_REF_NAME==cg_fpga_processing_system7_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconstant_1_0/cg_fpga_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconstant_1_0 || ORIG_REF_NAME==cg_fpga_xlconstant_1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconstant_1_1/cg_fpga_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconstant_1_1 || ORIG_REF_NAME==cg_fpga_xlconstant_1_1} -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_gpio_0_0/cg_fpga_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_gpio_0_0 || ORIG_REF_NAME==cg_fpga_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_gpio_0_0/cg_fpga_axi_gpio_0_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_gpio_0_0/cg_fpga_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_gpio_0_0 || ORIG_REF_NAME==cg_fpga_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_12_2_cg_fpga_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_0/cg_fpga_cg_fpga_axi_gpio_o1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_0/cg_fpga_cg_fpga_axi_gpio_o1_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_0/cg_fpga_cg_fpga_axi_gpio_o1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_1/cg_fpga_cg_fpga_axi_gpio_o1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_1/cg_fpga_cg_fpga_axi_gpio_o1_1_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_1/cg_fpga_cg_fpga_axi_gpio_o1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_i1_0/cg_fpga_cg_fpga_axi_gpio_i1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_i1_0/cg_fpga_cg_fpga_axi_gpio_i1_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_i1_0/cg_fpga_cg_fpga_axi_gpio_i1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_uartlite_0_0/cg_fpga_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_uartlite_0_0/cg_fpga_axi_uartlite_0_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_uartlite_0_0/cg_fpga_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_intc_0_0/cg_fpga_axi_intc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_intc_0_0/cg_fpga_axi_intc_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_intc_0_0/cg_fpga_axi_intc_0_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_rst_ps7_0_50M_0/cg_fpga_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_rst_ps7_0_50M_0 || ORIG_REF_NAME==cg_fpga_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_rst_ps7_0_50M_0/cg_fpga_rst_ps7_0_50M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_rst_ps7_0_50M_0 || ORIG_REF_NAME==cg_fpga_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_auto_pc_0/cg_fpga_auto_pc_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_v_vid_in_axi4s_0_0/cg_fpga_v_vid_in_axi4s_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cg_fpga_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_auto_pc_1/cg_fpga_auto_pc_1_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_vdma_0_0/cg_fpga_axi_vdma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_vdma_0_0/cg_fpga_axi_vdma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_vdma_0_0/cg_fpga_axi_vdma_0_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_processing_system7_0_0/cg_fpga_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_processing_system7_0_0 || ORIG_REF_NAME==cg_fpga_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/design_12_2_cg_fpga_0_0.xci
# IP: The module: 'design_12_2_cg_fpga_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_gpio_0_0/cg_fpga_axi_gpio_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_axi_gpio_0_0 || ORIG_REF_NAME==cg_fpga_axi_gpio_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_0/cg_fpga_cg_fpga_axi_gpio_o1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_1/cg_fpga_cg_fpga_axi_gpio_o1_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_i1_0/cg_fpga_cg_fpga_axi_gpio_i1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_uartlite_0_0/cg_fpga_axi_uartlite_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_axi_uartlite_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_intc_0_0/cg_fpga_axi_intc_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_axi_intc_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_rst_ps7_0_50M_0/cg_fpga_rst_ps7_0_50M_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_rst_ps7_0_50M_0 || ORIG_REF_NAME==cg_fpga_rst_ps7_0_50M_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xbar_1/cg_fpga_xbar_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xbar_1 || ORIG_REF_NAME==cg_fpga_xbar_1} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_auto_pc_0/cg_fpga_auto_pc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_auto_pc_0 || ORIG_REF_NAME==cg_fpga_auto_pc_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconcat_0_0/cg_fpga_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconcat_0_0 || ORIG_REF_NAME==cg_fpga_xlconcat_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconcat_1_0/cg_fpga_xlconcat_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconcat_1_0 || ORIG_REF_NAME==cg_fpga_xlconcat_1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_v_vid_in_axi4s_0_0/cg_fpga_v_vid_in_axi4s_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cg_fpga_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconcat_2_0/cg_fpga_xlconcat_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconcat_2_0 || ORIG_REF_NAME==cg_fpga_xlconcat_2_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconcat_3_0/cg_fpga_xlconcat_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconcat_3_0 || ORIG_REF_NAME==cg_fpga_xlconcat_3_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlslice_0_2/cg_fpga_xlslice_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlslice_0_2 || ORIG_REF_NAME==cg_fpga_xlslice_0_2} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlslice_0_3/cg_fpga_xlslice_0_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlslice_0_3 || ORIG_REF_NAME==cg_fpga_xlslice_0_3} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlslice_1_0/cg_fpga_xlslice_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlslice_1_0 || ORIG_REF_NAME==cg_fpga_xlslice_1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconstant_0_0/cg_fpga_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconstant_0_0 || ORIG_REF_NAME==cg_fpga_xlconstant_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xbar_0/cg_fpga_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xbar_0 || ORIG_REF_NAME==cg_fpga_xbar_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_auto_pc_1/cg_fpga_auto_pc_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_auto_pc_1 || ORIG_REF_NAME==cg_fpga_auto_pc_1} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_vdma_0_0/cg_fpga_axi_vdma_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_axi_vdma_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_processing_system7_0_0/cg_fpga_processing_system7_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_processing_system7_0_0 || ORIG_REF_NAME==cg_fpga_processing_system7_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconstant_1_0/cg_fpga_xlconstant_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconstant_1_0 || ORIG_REF_NAME==cg_fpga_xlconstant_1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_xlconstant_1_1/cg_fpga_xlconstant_1_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cg_fpga_xlconstant_1_1 || ORIG_REF_NAME==cg_fpga_xlconstant_1_1} -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_gpio_0_0/cg_fpga_axi_gpio_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_gpio_0_0 || ORIG_REF_NAME==cg_fpga_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_gpio_0_0/cg_fpga_axi_gpio_0_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_gpio_0_0/cg_fpga_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_gpio_0_0 || ORIG_REF_NAME==cg_fpga_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_12_2_cg_fpga_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_0/cg_fpga_cg_fpga_axi_gpio_o1_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_0/cg_fpga_cg_fpga_axi_gpio_o1_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_0/cg_fpga_cg_fpga_axi_gpio_o1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_1/cg_fpga_cg_fpga_axi_gpio_o1_1_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_1/cg_fpga_cg_fpga_axi_gpio_o1_1_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_o1_1/cg_fpga_cg_fpga_axi_gpio_o1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_o1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_i1_0/cg_fpga_cg_fpga_axi_gpio_i1_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_i1_0/cg_fpga_cg_fpga_axi_gpio_i1_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_cg_fpga_axi_gpio_i1_0/cg_fpga_cg_fpga_axi_gpio_i1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0 || ORIG_REF_NAME==cg_fpga_cg_fpga_axi_gpio_i1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_uartlite_0_0/cg_fpga_axi_uartlite_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_uartlite_0_0/cg_fpga_axi_uartlite_0_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_uartlite_0_0/cg_fpga_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_uartlite_0_0 || ORIG_REF_NAME==cg_fpga_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_intc_0_0/cg_fpga_axi_intc_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_intc_0_0/cg_fpga_axi_intc_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_intc_0_0 || ORIG_REF_NAME==cg_fpga_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_intc_0_0/cg_fpga_axi_intc_0_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_rst_ps7_0_50M_0/cg_fpga_rst_ps7_0_50M_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_rst_ps7_0_50M_0 || ORIG_REF_NAME==cg_fpga_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_rst_ps7_0_50M_0/cg_fpga_rst_ps7_0_50M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_rst_ps7_0_50M_0 || ORIG_REF_NAME==cg_fpga_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_auto_pc_0/cg_fpga_auto_pc_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_v_vid_in_axi4s_0_0/cg_fpga_v_vid_in_axi4s_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cg_fpga_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_auto_pc_1/cg_fpga_auto_pc_1_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_vdma_0_0/cg_fpga_axi_vdma_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_vdma_0_0/cg_fpga_axi_vdma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_axi_vdma_0_0 || ORIG_REF_NAME==cg_fpga_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_axi_vdma_0_0/cg_fpga_axi_vdma_0_0_ooc.xdc

# XDC: e:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/src/cg_fpga_processing_system7_0_0/cg_fpga_processing_system7_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cg_fpga_processing_system7_0_0 || ORIG_REF_NAME==cg_fpga_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
