# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab4/design_4/design_4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4 || ORIG_REF_NAME==design_4} -quiet] -quiet

# IP: D:/lab4/design_4/ip/design_4_cg_fpga_0_0/design_4_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_cg_fpga_0_0 || ORIG_REF_NAME==design_4_cg_fpga_0_0} -quiet] -quiet

# IP: D:/lab4/design_4/ip/design_4_adpt_in_0_0/design_4_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_adpt_in_0_0 || ORIG_REF_NAME==design_4_adpt_in_0_0} -quiet] -quiet

# IP: D:/lab4/design_4/ip/design_4_m7482_0_0/design_4_m7482_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_m7482_0_0 || ORIG_REF_NAME==design_4_m7482_0_0} -quiet] -quiet

# IP: D:/lab4/design_4/ip/design_4_m7482_1_0/design_4_m7482_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_m7482_1_0 || ORIG_REF_NAME==design_4_m7482_1_0} -quiet] -quiet

# IP: D:/lab4/design_4/ip/design_4_xor2_0_0/design_4_xor2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xor2_0_0 || ORIG_REF_NAME==design_4_xor2_0_0} -quiet] -quiet

# IP: D:/lab4/design_4/ip/design_4_xor2_1_0/design_4_xor2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xor2_1_0 || ORIG_REF_NAME==design_4_xor2_1_0} -quiet] -quiet

# IP: D:/lab4/design_4/ip/design_4_xor2_2_0/design_4_xor2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xor2_2_0 || ORIG_REF_NAME==design_4_xor2_2_0} -quiet] -quiet

# IP: D:/lab4/design_4/ip/design_4_xor2_3_0/design_4_xor2_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xor2_3_0 || ORIG_REF_NAME==design_4_xor2_3_0} -quiet] -quiet

# IP: D:/lab4/design_4/ip/design_4_adpt_out_0_0/design_4_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_adpt_out_0_0 || ORIG_REF_NAME==design_4_adpt_out_0_0} -quiet] -quiet

# IP: d:/lab4/design_4/ip/design_4_xor2_0_1/design_4_xor2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xor2_0_1 || ORIG_REF_NAME==design_4_xor2_0_1} -quiet] -quiet

# IP: d:/lab4/design_4/ip/design_4_xor2_1_1/design_4_xor2_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xor2_1_1 || ORIG_REF_NAME==design_4_xor2_1_1} -quiet] -quiet

# IP: d:/lab4/design_4/ip/design_4_xor2_2_1/design_4_xor2_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xor2_2_1 || ORIG_REF_NAME==design_4_xor2_2_1} -quiet] -quiet

# IP: d:/lab4/design_4/ip/design_4_m7482_0_1/design_4_m7482_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_m7482_0_1 || ORIG_REF_NAME==design_4_m7482_0_1} -quiet] -quiet

# IP: d:/lab4/design_4/ip/design_4_m7482_1_1/design_4_m7482_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_m7482_1_1 || ORIG_REF_NAME==design_4_m7482_1_1} -quiet] -quiet

# IP: d:/lab4/design_4/ip/design_4_xor2_3_1/design_4_xor2_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xor2_3_1 || ORIG_REF_NAME==design_4_xor2_3_1} -quiet] -quiet

# XDC: D:/lab4/design_4/design_4_ooc.xdc
