# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/lab10_/design_10/ip/design_10_rom0_64x24_0_0/design_10_rom0_64x24_0_0.xci
# IP: The module: 'design_10_rom0_64x24_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/lab10_/project_10/project_10.srcs/sources_1/ip/rom0/rom0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom0 || ORIG_REF_NAME==rom0} -quiet] -quiet

# IP: D:/lab10_/design_10/ip/design_10_rom0_64x24_0_0/design_10_rom0_64x24_0_0.xci
# IP: The module: 'design_10_rom0_64x24_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/lab10_/project_10/project_10.srcs/sources_1/ip/rom0/rom0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom0 || ORIG_REF_NAME==rom0} -quiet] -quiet
