# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: E:/lab12_/design_12_2/design_12_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2 || ORIG_REF_NAME==design_12_2} -quiet] -quiet

# IP: E:/lab12_/design_12_2/ip/design_12_2_cg_fpga_0_0/design_12_2_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2_cg_fpga_0_0 || ORIG_REF_NAME==design_12_2_cg_fpga_0_0} -quiet] -quiet

# IP: E:/lab12_/design_12_2/ip/design_12_2_ram_dp1_1Kx4_0_0/design_12_2_ram_dp1_1Kx4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2_ram_dp1_1Kx4_0_0 || ORIG_REF_NAME==design_12_2_ram_dp1_1Kx4_0_0} -quiet] -quiet

# IP: E:/lab12_/design_12_2/ip/design_12_2_ram_dp1_1Kx4_1_0/design_12_2_ram_dp1_1Kx4_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2_ram_dp1_1Kx4_1_0 || ORIG_REF_NAME==design_12_2_ram_dp1_1Kx4_1_0} -quiet] -quiet

# IP: E:/lab12_/design_12_2/ip/design_12_2_mux2_1_4bits_0_0/design_12_2_mux2_1_4bits_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2_mux2_1_4bits_0_0 || ORIG_REF_NAME==design_12_2_mux2_1_4bits_0_0} -quiet] -quiet

# IP: E:/lab12_/design_12_2/ip/design_12_2_adpt_in_0_0/design_12_2_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2_adpt_in_0_0 || ORIG_REF_NAME==design_12_2_adpt_in_0_0} -quiet] -quiet

# IP: E:/lab12_/design_12_2/ip/design_12_2_adpt_out_0_0/design_12_2_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2_adpt_out_0_0 || ORIG_REF_NAME==design_12_2_adpt_out_0_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_mux2_1_1bits_0_2/design_12_2_mux2_1_1bits_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2_mux2_1_1bits_0_2 || ORIG_REF_NAME==design_12_2_mux2_1_1bits_0_2} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_mux2_1_1bits_1_0/design_12_2_mux2_1_1bits_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2_mux2_1_1bits_1_0 || ORIG_REF_NAME==design_12_2_mux2_1_1bits_1_0} -quiet] -quiet

# IP: e:/lab12_/design_12_2/ip/design_12_2_xlconstant_0_0/design_12_2_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_2_xlconstant_0_0 || ORIG_REF_NAME==design_12_2_xlconstant_0_0} -quiet] -quiet

# XDC: E:/lab12_/design_12_2/design_12_2_ooc.xdc
