# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: E:/lab12/design_12/design_12.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12 || ORIG_REF_NAME==design_12} -quiet] -quiet

# IP: E:/lab12/design_12/ip/design_12_cg_fpga_0_0/design_12_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_cg_fpga_0_0 || ORIG_REF_NAME==design_12_cg_fpga_0_0} -quiet] -quiet

# IP: E:/lab12/design_12/ip/design_12_adpt_in_0_0/design_12_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_adpt_in_0_0 || ORIG_REF_NAME==design_12_adpt_in_0_0} -quiet] -quiet

# IP: E:/lab12/design_12/ip/design_12_adpt_out_0_0/design_12_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_adpt_out_0_0 || ORIG_REF_NAME==design_12_adpt_out_0_0} -quiet] -quiet

# IP: E:/lab12/design_12/ip/design_12_ram1_0_0/design_12_ram1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_ram1_0_0 || ORIG_REF_NAME==design_12_ram1_0_0} -quiet] -quiet

# IP: E:/lab12/design_12/ip/design_12_ram1_0_1/design_12_ram1_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_12_ram1_0_1 || ORIG_REF_NAME==design_12_ram1_0_1} -quiet] -quiet

# XDC: E:/lab12/design_12/design_12_ooc.xdc
