# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/cd2/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_cg_fpga_0_0/design_2_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_cg_fpga_0_0 || ORIG_REF_NAME==design_2_cg_fpga_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_adpt_in_0_2/design_2_adpt_in_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_adpt_in_0_2 || ORIG_REF_NAME==design_2_adpt_in_0_2} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_adpt_out_16bit_0_0/design_2_adpt_out_16bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_adpt_out_16bit_0_0 || ORIG_REF_NAME==design_2_adpt_out_16bit_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_adpt_in_1_0/design_2_adpt_in_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_adpt_in_1_0 || ORIG_REF_NAME==design_2_adpt_in_1_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_output_splitter_0_1/design_2_carry_output_splitter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_output_splitter_0_1 || ORIG_REF_NAME==design_2_carry_output_splitter_0_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_output_splitter_1_1/design_2_carry_output_splitter_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_output_splitter_1_1 || ORIG_REF_NAME==design_2_carry_output_splitter_1_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_output_splitter_2_1/design_2_carry_output_splitter_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_output_splitter_2_1 || ORIG_REF_NAME==design_2_carry_output_splitter_2_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_output_splitter_3_0/design_2_carry_output_splitter_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_output_splitter_3_0 || ORIG_REF_NAME==design_2_carry_output_splitter_3_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_6/design_2_xlconstant_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_6 || ORIG_REF_NAME==design_2_xlconstant_0_6} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_0_5/design_2_aggregator_4bit_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_0_5 || ORIG_REF_NAME==design_2_aggregator_4bit_0_5} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_7/design_2_xlconstant_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_7 || ORIG_REF_NAME==design_2_xlconstant_0_7} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_0_2/design_2_alu_74181_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_0_2 || ORIG_REF_NAME==design_2_alu_74181_0_2} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_1_2/design_2_alu_74181_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_1_2 || ORIG_REF_NAME==design_2_alu_74181_1_2} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_2_0/design_2_alu_74181_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_2_0 || ORIG_REF_NAME==design_2_alu_74181_2_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_lookahead_74182_0_0/design_2_carry_lookahead_74182_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_lookahead_74182_0_0 || ORIG_REF_NAME==design_2_carry_lookahead_74182_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_28/design_2_full_add_0_28.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_28 || ORIG_REF_NAME==design_2_full_add_0_28} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_13/design_2_and_gate_0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_13 || ORIG_REF_NAME==design_2_and_gate_0_13} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_16/design_2_full_add_0_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_16 || ORIG_REF_NAME==design_2_full_add_0_16} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_1/design_2_and_gate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_1 || ORIG_REF_NAME==design_2_and_gate_0_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_17/design_2_full_add_0_17.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_17 || ORIG_REF_NAME==design_2_full_add_0_17} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_2/design_2_and_gate_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_2 || ORIG_REF_NAME==design_2_and_gate_0_2} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_29/design_2_full_add_0_29.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_29 || ORIG_REF_NAME==design_2_full_add_0_29} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_14/design_2_and_gate_0_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_14 || ORIG_REF_NAME==design_2_and_gate_0_14} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_18/design_2_full_add_0_18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_18 || ORIG_REF_NAME==design_2_full_add_0_18} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_3/design_2_and_gate_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_3 || ORIG_REF_NAME==design_2_and_gate_0_3} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_19/design_2_full_add_0_19.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_19 || ORIG_REF_NAME==design_2_full_add_0_19} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_4/design_2_and_gate_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_4 || ORIG_REF_NAME==design_2_and_gate_0_4} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_20/design_2_full_add_0_20.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_20 || ORIG_REF_NAME==design_2_full_add_0_20} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_5/design_2_and_gate_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_5 || ORIG_REF_NAME==design_2_and_gate_0_5} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_21/design_2_full_add_0_21.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_21 || ORIG_REF_NAME==design_2_full_add_0_21} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_6/design_2_and_gate_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_6 || ORIG_REF_NAME==design_2_and_gate_0_6} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_22/design_2_full_add_0_22.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_22 || ORIG_REF_NAME==design_2_full_add_0_22} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_7/design_2_and_gate_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_7 || ORIG_REF_NAME==design_2_and_gate_0_7} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_23/design_2_full_add_0_23.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_23 || ORIG_REF_NAME==design_2_full_add_0_23} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_8/design_2_and_gate_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_8 || ORIG_REF_NAME==design_2_and_gate_0_8} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_24/design_2_full_add_0_24.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_24 || ORIG_REF_NAME==design_2_full_add_0_24} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_9/design_2_and_gate_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_9 || ORIG_REF_NAME==design_2_and_gate_0_9} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_25/design_2_full_add_0_25.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_25 || ORIG_REF_NAME==design_2_full_add_0_25} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_10/design_2_and_gate_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_10 || ORIG_REF_NAME==design_2_and_gate_0_10} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_26/design_2_full_add_0_26.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_26 || ORIG_REF_NAME==design_2_full_add_0_26} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_11/design_2_and_gate_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_11 || ORIG_REF_NAME==design_2_and_gate_0_11} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_27/design_2_full_add_0_27.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_27 || ORIG_REF_NAME==design_2_full_add_0_27} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_12/design_2_and_gate_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_12 || ORIG_REF_NAME==design_2_and_gate_0_12} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_0/design_2_full_add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_0 || ORIG_REF_NAME==design_2_full_add_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_0/design_2_and_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_0 || ORIG_REF_NAME==design_2_and_gate_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_30/design_2_full_add_0_30.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_30 || ORIG_REF_NAME==design_2_full_add_0_30} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_15/design_2_and_gate_0_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_15 || ORIG_REF_NAME==design_2_and_gate_0_15} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_1/design_2_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_1 || ORIG_REF_NAME==design_2_xlconstant_0_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_0_0/design_2_aggregator_4bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_0_0 || ORIG_REF_NAME==design_2_aggregator_4bit_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_0_1/design_2_aggregator_4bit_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_0_1 || ORIG_REF_NAME==design_2_aggregator_4bit_0_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_2/design_2_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_2 || ORIG_REF_NAME==design_2_xlconstant_0_2} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_3/design_2_xlconstant_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_3 || ORIG_REF_NAME==design_2_xlconstant_0_3} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_2_0/design_2_aggregator_4bit_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_2_0 || ORIG_REF_NAME==design_2_aggregator_4bit_2_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_3_0/design_2_aggregator_4bit_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_3_0 || ORIG_REF_NAME==design_2_aggregator_4bit_3_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_4/design_2_xlconstant_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_4 || ORIG_REF_NAME==design_2_xlconstant_0_4} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_0_0/design_2_alu_74181_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_0_0 || ORIG_REF_NAME==design_2_alu_74181_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_1_0/design_2_alu_74181_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_1_0 || ORIG_REF_NAME==design_2_alu_74181_1_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_0_2/design_2_aggregator_4bit_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_0_2 || ORIG_REF_NAME==design_2_aggregator_4bit_0_2} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_31/design_2_full_add_0_31.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_31 || ORIG_REF_NAME==design_2_full_add_0_31} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_16/design_2_and_gate_0_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_16 || ORIG_REF_NAME==design_2_and_gate_0_16} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_32/design_2_full_add_0_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_32 || ORIG_REF_NAME==design_2_full_add_0_32} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_17/design_2_and_gate_0_17.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_17 || ORIG_REF_NAME==design_2_and_gate_0_17} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_33/design_2_full_add_0_33.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_33 || ORIG_REF_NAME==design_2_full_add_0_33} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_18/design_2_and_gate_0_18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_18 || ORIG_REF_NAME==design_2_and_gate_0_18} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_34/design_2_full_add_0_34.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_34 || ORIG_REF_NAME==design_2_full_add_0_34} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_19/design_2_and_gate_0_19.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_19 || ORIG_REF_NAME==design_2_and_gate_0_19} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_35/design_2_full_add_0_35.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_35 || ORIG_REF_NAME==design_2_full_add_0_35} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_20/design_2_and_gate_0_20.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_20 || ORIG_REF_NAME==design_2_and_gate_0_20} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_36/design_2_full_add_0_36.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_36 || ORIG_REF_NAME==design_2_full_add_0_36} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_21/design_2_and_gate_0_21.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_21 || ORIG_REF_NAME==design_2_and_gate_0_21} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_37/design_2_full_add_0_37.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_37 || ORIG_REF_NAME==design_2_full_add_0_37} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_22/design_2_and_gate_0_22.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_22 || ORIG_REF_NAME==design_2_and_gate_0_22} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_38/design_2_full_add_0_38.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_38 || ORIG_REF_NAME==design_2_full_add_0_38} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_23/design_2_and_gate_0_23.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_23 || ORIG_REF_NAME==design_2_and_gate_0_23} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_39/design_2_full_add_0_39.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_39 || ORIG_REF_NAME==design_2_full_add_0_39} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_24/design_2_and_gate_0_24.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_24 || ORIG_REF_NAME==design_2_and_gate_0_24} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_40/design_2_full_add_0_40.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_40 || ORIG_REF_NAME==design_2_full_add_0_40} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_25/design_2_and_gate_0_25.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_25 || ORIG_REF_NAME==design_2_and_gate_0_25} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_41/design_2_full_add_0_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_41 || ORIG_REF_NAME==design_2_full_add_0_41} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_26/design_2_and_gate_0_26.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_26 || ORIG_REF_NAME==design_2_and_gate_0_26} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_42/design_2_full_add_0_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_42 || ORIG_REF_NAME==design_2_full_add_0_42} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_27/design_2_and_gate_0_27.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_27 || ORIG_REF_NAME==design_2_and_gate_0_27} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_43/design_2_full_add_0_43.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_43 || ORIG_REF_NAME==design_2_full_add_0_43} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_28/design_2_and_gate_0_28.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_28 || ORIG_REF_NAME==design_2_and_gate_0_28} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_44/design_2_full_add_0_44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_44 || ORIG_REF_NAME==design_2_full_add_0_44} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_29/design_2_and_gate_0_29.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_29 || ORIG_REF_NAME==design_2_and_gate_0_29} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_45/design_2_full_add_0_45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_45 || ORIG_REF_NAME==design_2_full_add_0_45} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_30/design_2_and_gate_0_30.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_30 || ORIG_REF_NAME==design_2_and_gate_0_30} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_full_add_0_46/design_2_full_add_0_46.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_full_add_0_46 || ORIG_REF_NAME==design_2_full_add_0_46} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_and_gate_0_31/design_2_and_gate_0_31.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_and_gate_0_31 || ORIG_REF_NAME==design_2_and_gate_0_31} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_5/design_2_xlconstant_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_5 || ORIG_REF_NAME==design_2_xlconstant_0_5} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_1_0/design_2_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_1_0 || ORIG_REF_NAME==design_2_xlconstant_1_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_0_3/design_2_aggregator_4bit_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_0_3 || ORIG_REF_NAME==design_2_aggregator_4bit_0_3} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_1_0/design_2_aggregator_4bit_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_1_0 || ORIG_REF_NAME==design_2_aggregator_4bit_1_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_2_0/design_2_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_2_0 || ORIG_REF_NAME==design_2_xlconstant_2_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_3_0/design_2_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_3_0 || ORIG_REF_NAME==design_2_xlconstant_3_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_2_1/design_2_aggregator_4bit_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_2_1 || ORIG_REF_NAME==design_2_aggregator_4bit_2_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_3_1/design_2_aggregator_4bit_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_3_1 || ORIG_REF_NAME==design_2_aggregator_4bit_3_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_4_0/design_2_xlconstant_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_4_0 || ORIG_REF_NAME==design_2_xlconstant_4_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_0_1/design_2_alu_74181_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_0_1 || ORIG_REF_NAME==design_2_alu_74181_0_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_1_1/design_2_alu_74181_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_1_1 || ORIG_REF_NAME==design_2_alu_74181_1_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_0_4/design_2_aggregator_4bit_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_0_4 || ORIG_REF_NAME==design_2_aggregator_4bit_0_4} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_8/design_2_xlconstant_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_8 || ORIG_REF_NAME==design_2_xlconstant_0_8} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_0_6/design_2_aggregator_4bit_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_0_6 || ORIG_REF_NAME==design_2_aggregator_4bit_0_6} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_1_1/design_2_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_1_1 || ORIG_REF_NAME==design_2_xlconstant_1_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_0_3/design_2_alu_74181_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_0_3 || ORIG_REF_NAME==design_2_alu_74181_0_3} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_1_3/design_2_alu_74181_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_1_3 || ORIG_REF_NAME==design_2_alu_74181_1_3} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_lookahead_74182_0_1/design_2_carry_lookahead_74182_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_lookahead_74182_0_1 || ORIG_REF_NAME==design_2_carry_lookahead_74182_0_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xor_gate_8bit_0_0/design_2_xor_gate_8bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xor_gate_8bit_0_0 || ORIG_REF_NAME==design_2_xor_gate_8bit_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xor_gate_8bit_0_1/design_2_xor_gate_8bit_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xor_gate_8bit_0_1 || ORIG_REF_NAME==design_2_xor_gate_8bit_0_1} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_output_splitter_4_0/design_2_carry_output_splitter_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_output_splitter_4_0 || ORIG_REF_NAME==design_2_carry_output_splitter_4_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_output_splitter_5_0/design_2_carry_output_splitter_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_output_splitter_5_0 || ORIG_REF_NAME==design_2_carry_output_splitter_5_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_0_9/design_2_xlconstant_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_9 || ORIG_REF_NAME==design_2_xlconstant_0_9} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_aggregator_4bit_0_7/design_2_aggregator_4bit_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_aggregator_4bit_0_7 || ORIG_REF_NAME==design_2_aggregator_4bit_0_7} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xlconstant_1_2/design_2_xlconstant_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_1_2 || ORIG_REF_NAME==design_2_xlconstant_1_2} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_0_4/design_2_alu_74181_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_0_4 || ORIG_REF_NAME==design_2_alu_74181_0_4} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_alu_74181_1_4/design_2_alu_74181_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_alu_74181_1_4 || ORIG_REF_NAME==design_2_alu_74181_1_4} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_lookahead_74182_0_2/design_2_carry_lookahead_74182_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_lookahead_74182_0_2 || ORIG_REF_NAME==design_2_carry_lookahead_74182_0_2} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_output_splitter_6_0/design_2_carry_output_splitter_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_output_splitter_6_0 || ORIG_REF_NAME==design_2_carry_output_splitter_6_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_carry_output_splitter_7_0/design_2_carry_output_splitter_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_carry_output_splitter_7_0 || ORIG_REF_NAME==design_2_carry_output_splitter_7_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_complement_16bit_con_0_0/design_2_complement_16bit_con_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_complement_16bit_con_0_0 || ORIG_REF_NAME==design_2_complement_16bit_con_0_0} -quiet] -quiet

# IP: D:/cd2/design_2/ip/design_2_xor_gate_0_0/design_2_xor_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xor_gate_0_0 || ORIG_REF_NAME==design_2_xor_gate_0_0} -quiet] -quiet

# XDC: D:/cd2/design_2/design_2_ooc.xdc
