# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/lab14/design_14/design_14.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14 || ORIG_REF_NAME==design_14} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_cg_fpga_0_0/design_14_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_cg_fpga_0_0 || ORIG_REF_NAME==design_14_cg_fpga_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_rom2_256x24_0_0/design_14_rom2_256x24_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_rom2_256x24_0_0 || ORIG_REF_NAME==design_14_rom2_256x24_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_UIR_0_0/design_14_UIR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_UIR_0_0 || ORIG_REF_NAME==design_14_UIR_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_adpt_in_0_0/design_14_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_adpt_in_0_0 || ORIG_REF_NAME==design_14_adpt_in_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_adpt_out_0_0/design_14_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_adpt_out_0_0 || ORIG_REF_NAME==design_14_adpt_out_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_and2_0_0/design_14_and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_and2_0_0 || ORIG_REF_NAME==design_14_and2_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_not1_0_0/design_14_not1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_not1_0_0 || ORIG_REF_NAME==design_14_not1_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_shifter_0_0/design_14_shifter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_shifter_0_0 || ORIG_REF_NAME==design_14_shifter_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_dff4_0_0/design_14_dff4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_dff4_0_0 || ORIG_REF_NAME==design_14_dff4_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_adder4_0_0/design_14_adder4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_adder4_0_0 || ORIG_REF_NAME==design_14_adder4_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_dff4_0_2/design_14_dff4_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_dff4_0_2 || ORIG_REF_NAME==design_14_dff4_0_2} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_dff4_0_1/design_14_dff4_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_dff4_0_1 || ORIG_REF_NAME==design_14_dff4_0_1} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_m74LS161_0_0/design_14_m74LS161_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_m74LS161_0_0 || ORIG_REF_NAME==design_14_m74LS161_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_addr_adpt_0_0/design_14_addr_adpt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_addr_adpt_0_0 || ORIG_REF_NAME==design_14_addr_adpt_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_m74LS161_0_1/design_14_m74LS161_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_m74LS161_0_1 || ORIG_REF_NAME==design_14_m74LS161_0_1} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_xlconstant_0_0/design_14_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_xlconstant_0_0 || ORIG_REF_NAME==design_14_xlconstant_0_0} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_and2_0_1/design_14_and2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_and2_0_1 || ORIG_REF_NAME==design_14_and2_0_1} -quiet] -quiet

# IP: D:/lab14/design_14/ip/design_14_and2_0_2/design_14_and2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_14_and2_0_2 || ORIG_REF_NAME==design_14_and2_0_2} -quiet] -quiet

# XDC: D:/lab14/design_14/design_14_ooc.xdc
